# Generated by Django 3.2.9 on 2021-11-19 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_auto_20211118_0650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['short_name'], 'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.OneToOneField(blank=True, help_text='Вариант оплаты', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paymentplan', to='tgbot.paymentplan', verbose_name='Вариант оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='promocode',
            field=models.OneToOneField(blank=True, default=None, help_text='Промокод', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='promocode', to='tgbot.promocode', verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.OneToOneField(blank=True, default='DELETED', help_text='Пользователь', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='пользователь', to='tgbot.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.IntegerField(default=10, verbose_name='Скидка, %'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='plan',
            field=models.OneToOneField(blank=True, help_text='Вариант оплаты', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocode', to='tgbot.paymentplan', verbose_name='Вариант оплаты'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='tests',
            field=models.ManyToManyField(blank=True, help_text='Тесты этой темы', related_name='test', to='tgbot.Test', verbose_name='Тесты'),
        ),
    ]
