# Generated by Django 3.2.9 on 2021-11-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_auto_20211119_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='tests',
            field=models.ManyToManyField(blank=True, help_text='Тесты этой темы', related_name='tests', to='tgbot.Test', verbose_name='Тесты'),
        ),
    ]
