# Generated by Django 3.2.9 on 2021-11-20 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_alter_theme_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.OneToOneField(blank=True, help_text='Вопрос этого ответа', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', related_query_name='answer', to='tgbot.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.OneToOneField(blank=True, help_text='Вариант оплаты', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', related_query_name='payment', to='tgbot.paymentplan', verbose_name='Вариант оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='promocode',
            field=models.OneToOneField(blank=True, default=None, help_text='Промокод', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='payments', related_query_name='payment', to='tgbot.promocode', verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.OneToOneField(blank=True, default='DELETED', help_text='Пользователь', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='payments', related_query_name='payment', to='tgbot.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(blank=True, help_text='Выпросы этого теста', related_name='tests', related_query_name='test', to='tgbot.Question', verbose_name='Вопросы'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='tests',
            field=models.ManyToManyField(blank=True, help_text='Тесты этой темы', related_name='themes', related_query_name='theme', to='tgbot.Test', verbose_name='Тесты'),
        ),
    ]
