# Generated by Django 3.2.9 on 2021-11-21 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_auto_20211120_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportmessage',
            options={'ordering': ['role'], 'verbose_name': 'Служебное сообщение', 'verbose_name_plural': 'Служебные сообщения'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Автор этого ответа', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', related_query_name='answer', to='tgbot.user', verbose_name='Автор ответа'),
        ),
    ]
