# Generated by Django 3.2.9 on 2021-11-21 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_auto_20211121_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, help_text='Вопрос этого ответа', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', related_query_name='answer', to='tgbot.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Автор этого ответа', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', related_query_name='answer', to='tgbot.user', verbose_name='Автор ответа'),
        ),
    ]
