# Generated by Django 3.2.9 on 2022-01-03 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0010_auto_20211125_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Пользователь', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='payments', related_query_name='payment', to='tgbot.user', verbose_name='Пользователь'),
        ),
    ]
