# Generated by Django 3.2.9 on 2022-01-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0011_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='available_words',
            field=models.TextField(blank=True, verbose_name='Доступные сокращения'),
        ),
    ]
