# Generated by Django 3.2.9 on 2022-01-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0013_auto_20220118_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='file_tg_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Id файла в телеграм'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='file_tg_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Id файла в телеграм'),
        ),
    ]
