# Generated by Django 3.2.9 on 2022-01-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0014_auto_20220118_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='file_tg_id',
            field=models.CharField(max_length=100, null=True, verbose_name='Id файла в телеграм'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='file_tg_id',
            field=models.CharField(max_length=100, null=True, verbose_name='Id файла в телеграм'),
        ),
    ]
